#!/bin/bash

#PBS -N phase
#PBS -l nodes=1:ppn=4
#PBS -l walltime=20:00:00
#PBS -o /projects/ps-gymreklab/helia/ensembl/biallelic/log
#PBS -e /projects/ps-gymreklab/helia/ensembl/biallelic/log
#PBS -A gymreklab-group
#PBS -q hotel
#PBS -V

echo $chr
source /home/hziaeija/miniconda3/bin/activate
conda activate ensemble_env

#remove duplicated positions and only keep the first one
bcftools norm -d all /projects/ps-gymreklab/helia/ensembl/ensemble_out/merged_chr"$chr"_sorted_ver2.vcf.gz -O z -o /projects/ps-gymreklab/helia/ensembl/biallelic/merged_chr"$chr"_unique.vcf.gz &&

#convert multiallelic to biallelic
bcftools norm -m-any /projects/ps-gymreklab/helia/ensembl/biallelic/merged_chr"$chr"_unique.vcf.gz -O z -o /projects/ps-gymreklab/helia/ensembl/biallelic/merged_chr"$chr"_biallelic.vcf.gz &&

tabix -p vcf /projects/ps-gymreklab/helia/ensembl/biallelic/merged_chr"$chr"_biallelic.vcf.gz &&

#phase
shapeit4 --input /projects/ps-gymreklab/helia/ensembl/biallelic/merged_chr"$chr"_biallelic.vcf.gz \
         --map /projects/ps-gymreklab/helia/ensembl/biallelic/recomb-hg38/genetic_map_GRCh38_chr"$chr".tab \
         --region chr"$chr" \
         --thread 5 \
         --output /projects/ps-gymreklab/helia/ensembl/biallelic/merged_chr"$chr"_biallelic_phased.vcf.gz &&

tabix -p vcf /projects/ps-gymreklab/helia/ensembl/biallelic/merged_chr"$chr"_biallelic_phased.vcf.gz &&

#convert biallelic to multiallelic
bcftools norm -m+any /projects/ps-gymreklab/helia/ensembl/biallelic/merged_chr"$chr"_biallelic_phased.vcf.gz -O z -o /projects/ps-gymreklab/helia/ensembl/biallelic/phased/merged_chr"$chr"_multiallelic_phased.vcf.gz &&

rm /projects/ps-gymreklab/helia/ensembl/biallelic/merged_chr"$chr"_biallelic.vcf.gz* &&
rm /projects/ps-gymreklab/helia/ensembl/biallelic/merged_chr"$chr"_unique.vcf.gz &&
rm /projects/ps-gymreklab/helia/ensembl/biallelic/merged_chr"$chr"_biallelic_phased.vcf.gz*

#remove loci without any alt allele
bcftools view -m2 --no-update /projects/ps-gymreklab/helia/ensembl/biallelic/phased/merged_chr"$chr"_multiallelic_phased.vcf.gz -O z -o /projects/ps-gymreklab/helia/ensembl/biallelic/phased/merged_chr"$chr"_phased_m2.vcf.gz

tabix -p vcf /projects/ps-gymreklab/helia/ensembl/biallelic/phased/merged_chr"$chr"_phased_m2.vcf.gz


