#!/bin/bash

#PBS -N longshot
#PBS -l nodes=1:ppn=5
#PBS -l walltime=30:00:00
#PBS -o /projects/ps-gymreklab/helia/ensembl/biallelic/log
#PBS -e /projects/ps-gymreklab/helia/ensembl/biallelic/log
#PBS -A gymreklab-group
#PBS -q hotel
#PBS -V



echo $chr

time longshot -r chr$chr \
		--bam /projects/ps-gymreklab/helia/ensembl/biallelic/validation/LR/NA19030.aligned.sorted.bam \
		--ref /projects/ps-gymreklab/helia/long_read_final_experiments/metadata/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta \
		--out /projects/ps-gymreklab/helia/ensembl/biallelic/validation/LR/NA19030_variation_chr"$chr".vcf \
		--out_bam /projects/ps-gymreklab/helia/ensembl/biallelic/validation/LR/NA19030_happlotagged_chr"$chr".bam &&

bgzip /projects/ps-gymreklab/helia/ensembl/biallelic/validation/LR/NA19030_variation_chr"$chr".vcf 
